import type { Types } from "mongoose";
import type { AuthProvider } from "./auth.types";

export interface PreferenceProps {
  theme: "light" | "dark";
  workStartHour: number;
  workEndHour: number;
  notifications: boolean;
  defaultRitual: string;
}

export interface UserDocument {
  _id: Types.ObjectId;
  username: string;
  email: string;
  avatar?: string;
  avatarPublicId?: string;
  authProvider: AuthProvider;
  preferences: PreferenceProps;
  isEmailVerified: boolean;
}

export interface GetRequestPayloads {
  page?: string;
  limit?: string;
  sortBy?: string;
  order?: string;
  search?: string;
}

// Context Types
export type CognitiveLoad = "low" | "medium" | "high";
export type EmotionalTone = "calm" | "energetic" | "analytical" | "creative";
export type EnergyLevel = "low" | "medium" | "high";

// Ritual Types
export type RitualType = "custom" | "template";
export type StepType = "breathe" | "braindump" | "move" | "intention" | "pause";

export interface StepsProps {
  type: StepType;
  duration: number;
  prompt: string;
  audioFile?: string;
}

export interface TargetTransitionProps {
  fromContext?: string;
  toContext?: string;
}

// Analytics Types
export interface AnalyticsResponse {
  // Used by: AnalyticsKeyMetrics
  keyMetrics: {
    totalFocusTime: string; // "14h 32m"
    totalFocusMinutes: number; // 872 (for calculations)
    averageFocusScore: number; // 78 (percentage, 0-100)
    focusScoreChange: number; // +5 (compared to previous period)
    totalSessions: number; // 23
    totalContextSwitches: number; // 18
    ritualComplianceRate: number; // 77 (percentage)
    switchesWithRitual: number; // 14
    switchesTotal: number; // 18
  };

  // Used by: AnalyticsDailyFocusChart
  dailyFocusData: Array<{
    day: string; // "Monday", "Tuesday"...
    date: string; // "2025-01-13"
    focus: number; // 82 (avg focus score for that day)
    sessions: number; // 3
    focusMinutes: number; // 240
  }>;

  // Used by: AnalyticsContextPerformance
  contextPerformance: Array<{
    contextId: string;
    name: string; // "Deep Work"
    color: string; // "#2E86AB"
    icon: string; // "🧠"
    avgFocus: number; // 85
    sessions: number; // 8
    totalTime: string; // "6h 20m"
    totalMinutes: number; // 380
  }>;

  // Used by: AnalyticsContextSwitchHeatmap
  contextSwitches: Array<{
    from: string; // "Deep Work"
    fromIcon: string; // "🧠"
    to: string; // "Meetings"
    toIcon: string; // "📞"
    count: number; // 5
    avgFocus: number; // 62
    difficulty: "Easy" | "Medium" | "Hard";
  }>;

  // Used by: AnalyticsMonthlyTrend
  focusTrendData: Array<{
    week: string; // "Week 1", "Week 2"
    avgFocus: number; // 74
    sessions: number; // 12
    startDate: string;
  }>;

  // Used by: AnalyticsInsights (generated by backend logic)
  insights: Array<{
    type: "success" | "warning" | "info" | "tip";
    icon: string; // emoji
    title: string;
    description: string;
    action: string;
  }>;

  // Metadata
  period: {
    timeRange: string; // "week"
    from: string; // ISO date
    to: string; // ISO date
    previousFrom: string; // for comparison
    previousTo: string;
  };
}
